name: Continuous integration

on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: UI E2E Tests
        uses: cypress-io/github-action@v4
        with:
          browser: edge
          headed: false
